// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phgrwmrxcryhkkmjkpqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZ3J3bXJ4Y3J5aGtrbWprcHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzQ3NjYsImV4cCI6MjA2MTY1MDc2Nn0.dOi7rcV6DcU0lncOOeGdiuPgpL0nPqrGSHdY8tzIc9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);